name: Test Build Server

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Check system
        shell: bash
        run: |
          echo "=== CPU ==="
          nproc

          echo "=== RAM ==="
          free -h

          echo "=== STORAGE ==="
          df -h
